services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio_data:/data

  postgres_dwh:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DWH_DB}
      POSTGRES_USER: ${DWH_USER}
      POSTGRES_PASSWORD: ${DWH_PASSWORD}
    volumes:
      - postgres_dwh_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./:/app
    depends_on:
      - postgres_dwh
      - redis

  streamlit:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - postgres_dwh
      - minio

  dagster:
    build: .
    command: dagster dev -h 0.0.0.0 -p 3000 -m pipeline.orchestration
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - ./:/app
      - dagster_data:/opt/dagster/dagster_home
    depends_on:
      - postgres_dwh
      - minio

volumes:
  minio_data:
  postgres_dwh_data:
  dagster_data: